### ISSUE TITLE
Not able to run my own data 

### ISSUE THREAD

**Issue by gsh89** [uts-magic-lab/slam_glass#6]
Hello. Thanks for sharing your work. I was able to successfully build the package and run the launch file with your bag files and reproduce the results mentioned in your paper. 

However, I wanted to run the data that I recorded on my robot in a bag file to see how the results are  in that case. I do not get any map output. I made sure that I set the use_sim_time to true, since the laser scan topic in  my bag file is /scan so I did not remap it and included the static transforms in  the launch file. I also echoed the /scan topic to make sure both range and intensity values are included. I still can't figure out why no map is being output. Your help will be greatly appreciated.

**Comment by gaohe1997** [comment]
Hello. Have you solved the problem above? 
I can get the output, but the detection result is not so good. 
Any idea, please contect 572083497@qq.com.

**Comment by GaH703** [comment]
Hello. Have you solved the problem above?
I can get the output, but the detection result is not so good.
Any idea, please contact 572083497@qq.com.

**Comment by kunle12** [comment]
Have you calibrate your laser sensor as described in the paper? Without access to any of additional (your) data, there is not much I can do.

**Comment by gaohe1997** [comment]
Thank you for your reply.
I run the program on linux 16.04 , ros kinetic. Your data works well.
But I've got an error as figure 1 when running my own rosbag.
I've already done that：
1. Compile the program.
2. Comment line 6 and 7 in slam_glass_pr2.launch to uniform topic name.
2. Uncommenting line 80 in CMakeFiles.txt and recompile.
3. Calibrate the sensor as figure 2.
4. In slam_glass_pr2.launch : set the "glasstrigintensity"  to 80 ; set the "glassintensityDelta"  to 100; 
5. Add a visual marker in Rviz for trajector.
6. roslaunch+play my own rosbag. 

I have been unable to apply my data to your algorithm due to errors. Your help will be greatly appreciated.
Rosbag and figure were compressed into the file below
[new_bag.zip](https://github.com/uts-magic-lab/slam_glass/files/6073930/new_bag.zip)

Any issues, please contact 572083497@qq.com, thanks.

**Comment by GaH703** [comment]
Thank you for your reply.
I run the program on Ubuntu 16.04 , ros kinetic. Your data works well.
But I've got an error as figure 1 when running my own rosbag.
I've already done that：

1. Compile the program.
2. Comment line 6 and 7 in slam_glass_pr2.launch to uniform topic name.
3. Uncommenting line 80 in CMakeFiles.txt and recompile.
4. Calibrate the sensor as figure 2.
5. In slam_glass_pr2.launch : set the "glasstrigintensity" to 80 ; set the "glassintensityDelta" to 100;
6. Add a visual marker in Rviz for trajectory.
7. play my own rosbag + roslaunch.
I have been unable to apply my data to your algorithm due to errors. 
Could you try out my data? Your help will be greatly appreciated.
Rosbag and figure were compressed into the file below
[new_bag.zip](https://github.com/uts-magic-lab/slam_glass/files/6073966/new_bag.zip)

Any issues, please contact 572083497@qq.com, thanks.

**Comment by kunle12** [comment]
I don't have a 16.04 box at the moment. It will take me sometime (I have to find some weekend spare time for this) to set up the environment since I haven't continued with this work for a very long time. Have you tried to run your data in the original gslam code successfully? It will be also very useful if you can run slam_glass under gdb and provide a stack backtrace. It will make debugging much easier.

**Comment by GaH703** [comment]
I have tried the default Gmapping package in ROS. Both your data and mine can run successfully.
I will continue to debug  according to your suggestion. 
Keep in touch, thank you!

**Comment by kunle12** [comment]
I finally had some time to do some debugging. It seems that slam_glass does not crash when it is compiled in full debugging mode. I encountered many "glassmatch hit invalid point (-459,2276) phit (-72.959744,63.779548) r= 100.000000 angle -1.082104, cptheta = -2.812180" error while I was running the program. I need to investigate further to know what is going on.

**Comment by kunle12** [comment]
I fixed the crash error, you can checkout out the latest code. It seems that your input data with such small intensity filtering threshold, (the delta is bigger than the threshold) basically rendered the simple algorithm implemented in slam_glass unworkable and useless. You should either get a laser sensor with better intensity responses or find an alternative method/algorithm for your use.
